server:
  port: 8080

spring:
  application:
    name: market-allar
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    open-in-view: false

  # TODO: mariadb datasource
  # h2 db datasource
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MariaDB
    username: sa
    password:

  # Kafka 설정
  kafka:
    bootstrap-servers: localhost:29092  # Docker로 실행한 Kafka 서버 주소
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: my-app-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.demo.model"  # JSON deserialize 허용할 패키지

  # MongoDB 설정
  data:
    mongodb:
      host: localhost
      port: 27017
      database: myapp
      username: root
      password: example
      authentication-database: admin

# 애플리케이션 설정
app:
  kafka:
    topics:
      order-topic: order-events
      user-topic: user-events

external:
  payment:
    api:
      url: https://allar-market.free.beeceptor.com


